local aho = require("santoku.learn.aho")
local ivec = require("santoku.ivec")
local pvec = require("santoku.pvec")
local test = require("santoku.test")

test("aho", function ()

  test("basic matching", function ()
    local ids = ivec.create({ 10, 20, 30 })
    local ac = aho.create({ ids = ids, patterns = { "foo", "bar", "baz" } })
    local offsets, mids, starts, ends = ac:predict({ texts = { "foo bar baz" } })
    assert(offsets:size() == 2)
    assert(offsets:get(0) == 0)
    assert(offsets:get(1) == 3)
    assert(mids:size() == 3)
    assert(mids:get(0) == 10)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 3)
    assert(mids:get(1) == 20)
    assert(starts:get(1) == 4)
    assert(ends:get(1) == 7)
    assert(mids:get(2) == 30)
    assert(starts:get(2) == 8)
    assert(ends:get(2) == 11)
  end)

  test("case insensitive", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "hello" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "HELLO world" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 5)
  end)

  test("case insensitive pattern", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "WORLD" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "hello world" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 6)
    assert(ends:get(0) == 11)
  end)

  test("diacritic text matches plain pattern", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "cafe" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "caf\195\169" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 5)
  end)

  test("diacritic pattern matches plain text", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "caf\195\169" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "cafe latte" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 4)
  end)

  test("diacritic both sides", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "r\195\169sum\195\169" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "my R\195\137SUM\195\137 here" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 3)
    assert(ends:get(0) == 11)
  end)

  test("position after multibyte prefix", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "world" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "h\195\169llo world" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 7)
    assert(ends:get(0) == 12)
  end)

  test("longest match filtering", function ()
    local ids = ivec.create({ 1, 2 })
    local ac = aho.create({ ids = ids, patterns = { "new", "new york" } })
    local _, mids, starts, ends = ac:predict({ texts = { "new york city" }, longest = true })
    assert(mids:size() == 1)
    assert(mids:get(0) == 2)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 8)
  end)

  test("overlapping without longest", function ()
    local ids = ivec.create({ 1, 2 })
    local ac = aho.create({ ids = ids, patterns = { "ab", "abc" } })
    local _, mids = ac:predict({ texts = { "abcd" } })
    assert(mids:size() == 2)
  end)

  test("multiple texts", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "hi" } })
    local offsets, mids = ac:predict({ texts = { "hi there", "say hi", "none" } })
    assert(offsets:size() == 4)
    assert(offsets:get(0) == 0)
    assert(offsets:get(1) == 1)
    assert(offsets:get(2) == 2)
    assert(offsets:get(3) == 2)
    assert(mids:size() == 2)
  end)

  test("no matches", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "xyz" } })
    local offsets, mids = ac:predict({ texts = { "abc def" } })
    assert(mids:size() == 0)
    assert(offsets:get(0) == 0)
    assert(offsets:get(1) == 0)
  end)

  test("persist and load string", function ()
    local ids = ivec.create({ 5, 10 })
    local ac = aho.create({ ids = ids, patterns = { "alpha", "beta" } })
    local s = ac:persist(true)
    local ac2 = aho.load(s, true)
    local _, mids, starts, ends = ac2:predict({ texts = { "alpha and beta" } })
    assert(mids:size() == 2)
    assert(mids:get(0) == 5)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 5)
    assert(mids:get(1) == 10)
    assert(starts:get(1) == 10)
    assert(ends:get(1) == 14)
  end)

  test("latin extended-a", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "scev" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "\197\161\196\141ev" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 6)
  end)

  test("combining marks dropped", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "cafe" }, normalize = true })
    local _, mids, starts, ends = ac:predict({ texts = { "cafe\204\129" } })
    assert(mids:size() == 1)
    assert(mids:get(0) == 1)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 4)
  end)

  test("empty text", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "x" } })
    local offsets, mids = ac:predict({ texts = { "" } })
    assert(mids:size() == 0)
    assert(offsets:get(0) == 0)
    assert(offsets:get(1) == 0)
  end)

  test("multiple matches same text", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "ab" } })
    local _, mids, starts, ends = ac:predict({ texts = { "ab ab ab" } })
    assert(mids:size() == 3)
    assert(starts:get(0) == 0)
    assert(ends:get(0) == 2)
    assert(starts:get(1) == 3)
    assert(ends:get(1) == 5)
    assert(starts:get(2) == 6)
    assert(ends:get(2) == 8)
  end)

  test("tag basic", function ()
    local ids = ivec.create({ 10, 20 })
    local ac = aho.create({ ids = ids, patterns = { "foo", "bar" } })
    local result = ac:tag({ texts = { "foo and bar" }, fmt = "[%match:%id]" })
    assert(result[1] == "[foo:10] and [bar:20]")
  end)

  test("tag with names", function ()
    local ids = ivec.create({ 1, 2 })
    local ac = aho.create({
      ids = ids,
      patterns = { "nyc", "la" },
      names = { "New York City", "Los Angeles" }
    })
    local result = ac:tag({ texts = { "visit nyc or la" }, fmt = '<span title="%name">%match</span>' })
    assert(result[1] == 'visit <span title="New York City">nyc</span> or <span title="Los Angeles">la</span>')
  end)

  test("tag preserves original case", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "hello" }, normalize = true })
    local result = ac:tag({ texts = { "say HELLO there" }, fmt = "[%match]" })
    assert(result[1] == "say [HELLO] there")
  end)

  test("tag preserves diacritics in match", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "cafe" }, normalize = true })
    local result = ac:tag({ texts = { "at caf\195\169 now" }, fmt = "[%match]" })
    assert(result[1] == "at [caf\195\169] now")
  end)

  test("tag no matches returns original", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "xyz" } })
    local result = ac:tag({ texts = { "abc def" }, fmt = "[%match]" })
    assert(result[1] == "abc def")
  end)

  test("tag multiple texts", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "hi" } })
    local result = ac:tag({ texts = { "hi there", "say hi" }, fmt = "(%match)" })
    assert(result[1] == "(hi) there")
    assert(result[2] == "say (hi)")
  end)

  test("tag literal percent", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "x" } })
    local result = ac:tag({ texts = { "x" }, fmt = "100%% %match" })
    assert(result[1] == "100% x")
  end)

  test("tag longest filtering", function ()
    local ids = ivec.create({ 1, 2 })
    local ac = aho.create({
      ids = ids,
      patterns = { "new", "new york" },
      names = { "new", "New York" }
    })
    local result = ac:tag({ texts = { "new york city" }, fmt = "[%name]", longest = true })
    assert(result[1] == "[New York] city")
  end)

  test("tag html escape match", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "a&b" } })
    local result = ac:tag({ texts = { "see a&b here" }, fmt = "<b>%hmatch</b>" })
    assert(result[1] == "see <b>a&amp;b</b> here")
  end)

  test("tag html escape name", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({
      ids = ids,
      patterns = { "foo" },
      names = { '<script>alert("x")</script>' }
    })
    local result = ac:tag({ texts = { "foo" }, fmt = '%hname' })
    assert(result[1] == '&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;')
  end)

  test("tag html escape vs raw", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "x<y" } })
    local result = ac:tag({ texts = { "x<y" }, fmt = "%match|%hmatch" })
    assert(result[1] == "x<y|x&lt;y")
  end)

  test("tag html escape single quotes", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({
      ids = ids,
      patterns = { "it" },
      names = { "it's" }
    })
    local result = ac:tag({ texts = { "it works" }, fmt = "<span title='%hname'>%hmatch</span>" })
    assert(result[1] == "<span title='it&#39;s'>it</span> works")
  end)

  test("tag persist load with names", function ()
    local ids = ivec.create({ 5, 10 })
    local ac = aho.create({
      ids = ids,
      patterns = { "alpha", "beta" },
      names = { "Alpha Entity", "Beta Entity" }
    })
    local s = ac:persist(true)
    local ac2 = aho.load(s, true)
    local result = ac2:tag({ texts = { "alpha and beta" }, fmt = "%name(%id)" })
    assert(result[1] == "Alpha Entity(5) and Beta Entity(10)")
  end)

  test("predict with exclude", function ()
    local ids = ivec.create({ 1, 2, 3 })
    local ac = aho.create({ ids = ids, patterns = { "foo", "bar", "baz" } })
    local exc = pvec.create()
    exc:push(0, 3)
    local _, mids = ac:predict({
      texts = { "foo bar baz" },
      exclude = exc
    })
    assert(mids:size() == 2)
    assert(mids:get(0) == 2)
    assert(mids:get(1) == 3)
  end)

  test("tag with exclude", function ()
    local ids = ivec.create({ 1, 2 })
    local ac = aho.create({ ids = ids, patterns = { "foo", "bar" } })
    local exc = pvec.create()
    exc:push(0, 3)
    local result = ac:tag({
      texts = { "foo and bar" },
      fmt = "[%match]",
      exclude = exc
    })
    assert(result[1] == "foo and [bar]")
  end)

  test("exclude partial overlap drops match", function ()
    local ids = ivec.create({ 1 })
    local ac = aho.create({ ids = ids, patterns = { "bar baz" } })
    local exc = pvec.create()
    exc:push(0, 5)
    local _, mids = ac:predict({
      texts = { "foo bar baz" },
      exclude = exc
    })
    assert(mids:size() == 0)
  end)

end)
